name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Install Docker
              run: |
                sudo apt-get update
                sudo apt-get install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
                - name: Add user to Docker group
                 run: sudo usermod -aG docker $USER
                  - name: Start Docker service
                      run: |
                        sudo systemctl start docker
                        sudo systemctl enable docker
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:24-assignment1
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh
